//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaSnacks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Articulo()
        {
            this.Lineas = new HashSet<Linea>();

        }
        private VentaSnackEntities1 db = new VentaSnackEntities1();
        public string idArticulo { get; set; }
        public string nombre { get; set; }
        public decimal costo { get; set; }
        public bool promocion { get; set; }
        public byte[] imagen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Linea> Lineas { get; set; }

        public decimal TotalLinea(Linea l)
        {
            decimal total = 0;

            VentaSnacks.Models.Articulo ar = db.Articuloes.Find(l.idArticulo); 

            if (ar.promocion == true)
            {
                if (l.cantidad % 2 == 0)
                {
                    total = Convert.ToDecimal(ar.costo * (l.cantidad / 2));
                }
                else
                {
                    total = (Convert.ToDecimal(ar.costo * (l.cantidad / 2)) + ar.costo);
                }
            }
            else
            {
                total = (ar.costo * l.cantidad);
            }

            return total;
        }

        public Articulo buscaArticulo(int id)
        {
            Articulo ar = db.Articuloes.Find(id);
            return ar;
        }

    }
}
