//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaSnacks.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Data.Entity;

    public partial class User
    {

        private VentaSnackEntities1 db = new VentaSnackEntities1();
        public string idUser { get; set; }

        [DataType(DataType.Password)]
        public string password { get; set; }
        public string nombre { get; set; }

        public User validaUsuario(string id, string pass)
        {
            User use = db.Users.Find(id);
            User us = db.Users.Where(x => x.idUser == id && x.password == pass).FirstOrDefault();
            return us;
        }
    }
}
